#include "../../../../src/sl/morph/hin/analyser/defn.h"
#include "const.h"
char fe_info[TOTAL_FE_INFO][INFOSIZE]={
"n gender m case d number sg ",
"n gender m case d number pl ",
"n gender m case o number sg ",
"n gender m case o number pl ",
"n gender f case d number sg ",
"n gender f case d number pl ",
"n gender f case o number sg ",
"n gender f case o number pl ",
"v tam eM gender any number sg person 1 ",
"v tam eM gender any number sg person 2 ",
"v tam eM gender any number sg person 2h ",
"v tam eM gender any number sg person 3 ",
"v tam eM gender any number pl person 1 ",
"v tam eM gender any number pl person 2 ",
"v tam eM gender any number pl person 2h ",
"v tam eM gender any number pl person 3 ",
"v tam gA gender m number sg person 1 ",
"v tam gA gender m number sg person 2 ",
"v tam gA gender m number sg person 2h ",
"v tam gA gender m number sg person 3 ",
"v tam gA gender m number pl person 1 ",
"v tam gA gender m number pl person 2 ",
"v tam gA gender m number pl person 2h ",
"v tam gA gender m number pl person 3 ",
"v tam gA gender f number sg person 1 ",
"v tam gA gender f number sg person 2 ",
"v tam gA gender f number sg person 2h ",
"v tam gA gender f number sg person 3 ",
"v tam gA gender f number pl person 1 ",
"v tam gA gender f number pl person 2 ",
"v tam gA gender f number pl person 2h ",
"v tam gA gender f number pl person 3 ",
"v tam yA gender m number sg person any ",
"v tam yA gender m number pl person any ",
"v tam yA gender f number sg person any ",
"v tam yA gender f number pl person any ",
"v tam hE gender any number sg person 1 ",
"v tam hE gender any number sg person 2 ",
"v tam hE gender any number sg person 3 ",
"v tam hE gender any number pl person 1 ",
"v tam hE gender any number pl person 2 ",
"v tam hE gender any number pl person 3 ",
"v tam WA gender m number sg person any ",
"v tam WA gender m number pl person any ",
"v tam WA gender f number sg person any ",
"v tam WA gender f number pl person any ",
"v tam yA gender m number sg person any ",
"v tam yA gender m number pl person any ",
"v tam yA gender f number sg person any ",
"v tam yA gender f number pl person any ",
"v tam kara gender any number any person any ",
"psp",
"adv",
"psp",
"avy",
"avy",
"pn person 1 number sg gender any case o parsarg 0 ",
"pn person 1 number sg gender any case o parsarg ne ",
"pn person 1 number sg gender any case o parsarg ko ",
"pn person 1 number sg gender any case o parsarg se ",
"pn person 1 number sg gender any case o parsarg meM ",
"pn person 1 number sg gender any case o parsarg para ",
"pn person 1 number pl gender any case o parsarg 0 ",
"pn person 1 number pl gender any case o parsarg ne ",
"pn person 1 number pl gender any case o parsarg ko ",
"pn person 1 number pl gender any case o parsarg se ",
"pn person 1 number pl gender any case o parsarg meM ",
"pn person 1 number pl gender any case o parsarg para ",
"pn person 2 number sg gender any case o parsarg 0 ",
"pn person 2 number sg gender any case o parsarg ne ",
"pn person 2 number sg gender any case o parsarg ko ",
"pn person 2 number sg gender any case o parsarg se ",
"pn person 2 number sg gender any case o parsarg meM ",
"pn person 2 number sg gender any case o parsarg para ",
"pn person 2 number pl gender any case o parsarg 0 ",
"pn person 2 number pl gender any case o parsarg ne ",
"pn person 2 number pl gender any case o parsarg ko ",
"pn person 2 number pl gender any case o parsarg se ",
"pn person 2 number pl gender any case o parsarg meM ",
"pn person 2 number pl gender any case o parsarg para ",
"pn person 3 number sg gender any case o parsarg 0 ",
"pn person 3 number sg gender any case o parsarg ne ",
"pn person 3 number sg gender any case o parsarg ko ",
"pn person 3 number sg gender any case o parsarg se ",
"pn person 3 number sg gender any case o parsarg meM ",
"pn person 3 number sg gender any case o parsarg para ",
"pn person 3 number pl gender any case o parsarg 0 ",
"pn person 3 number pl gender any case o parsarg ne ",
"pn person 3 number pl gender any case o parsarg ko ",
"pn person 3 number pl gender any case o parsarg se ",
"pn person 3 number pl gender any case o parsarg meM ",
"pn person 3 number pl gender any case o parsarg para ",
"pn person 1 number sg gender any case d parsarg 0 ",
"pn person 1 number pl gender any case d parsarg 0 ",
"pn person 2 number sg gender any case d parsarg 0 ",
"pn person 2 number pl gender any case d parsarg 0 ",
"pn person 3 number sg gender any case d parsarg 0 ",
"pn person 3 number pl gender any case d parsarg 0 ",
"pn person any number any gender any case o parsarg 0 ",
"pn person any number any gender any case o parsarg ne ",
"pn person any number any gender any case o parsarg ko ",
"pn person any number any gender any case o parsarg se ",
"pn person any number any gender any case o parsarg meM ",
"pn person any number any gender any case o parsarg para ",
"sh_P person 3 number sg gender m case d number sg parsarg kA ",
"sh_P person 3 number sg gender m case d number pl parsarg kA ",
"sh_P person 3 number sg gender m case o number sg parsarg kA ",
"sh_P person 3 number sg gender m case o number pl parsarg kA ",
"sh_P person 3 number sg gender f case d number sg parsarg kA ",
"sh_P person 3 number sg gender f case d number pl parsarg kA ",
"sh_P person 3 number sg gender f case o number sg parsarg kA ",
"sh_P person 3 number sg gender f case o number pl parsarg kA ",
"sh_P person 3 number pl gender m case d number sg parsarg kA ",
"sh_P person 3 number pl gender m case d number pl parsarg kA ",
"sh_P person 3 number pl gender m case o number sg parsarg kA ",
"sh_P person 3 number pl gender m case o number pl parsarg kA ",
"sh_P person 3 number pl gender f case d number sg parsarg kA ",
"sh_P person 3 number pl gender f case d number pl parsarg kA ",
"sh_P person 3 number pl gender f case o number sg parsarg kA ",
"sh_P person 3 number pl gender f case o number pl parsarg kA ",
"sh_P person 2 number sg gender m case d number sg parsarg kA ",
"sh_P person 2 number sg gender m case d number pl parsarg kA ",
"sh_P person 2 number sg gender m case o number sg parsarg kA ",
"sh_P person 2 number sg gender m case o number pl parsarg kA ",
"sh_P person 2 number sg gender f case d number sg parsarg kA ",
"sh_P person 2 number sg gender f case d number pl parsarg kA ",
"sh_P person 2 number sg gender f case o number sg parsarg kA ",
"sh_P person 2 number sg gender f case o number pl parsarg kA ",
"sh_P person 2 number pl gender m case d number sg parsarg kA ",
"sh_P person 2 number pl gender m case d number pl parsarg kA ",
"sh_P person 2 number pl gender m case o number sg parsarg kA ",
"sh_P person 2 number pl gender m case o number pl parsarg kA ",
"sh_P person 2 number pl gender f case d number sg parsarg kA ",
"sh_P person 2 number pl gender f case d number pl parsarg kA ",
"sh_P person 2 number pl gender f case o number sg parsarg kA ",
"sh_P person 2 number pl gender f case o number pl parsarg kA ",
"sh_P person 1 number sg gender m case d number sg parsarg kA ",
"sh_P person 1 number sg gender m case d number pl parsarg kA ",
"sh_P person 1 number sg gender m case o number sg parsarg kA ",
"sh_P person 1 number sg gender m case o number pl parsarg kA ",
"sh_P person 1 number sg gender f case d number sg parsarg kA ",
"sh_P person 1 number sg gender f case d number pl parsarg kA ",
"sh_P person 1 number sg gender f case o number sg parsarg kA ",
"sh_P person 1 number sg gender f case o number pl parsarg kA ",
"sh_P person 1 number pl gender m case d number sg parsarg kA ",
"sh_P person 1 number pl gender m case d number pl parsarg kA ",
"sh_P person 1 number pl gender m case o number sg parsarg kA ",
"sh_P person 1 number pl gender m case o number pl parsarg kA ",
"sh_P person 1 number pl gender f case d number sg parsarg kA ",
"sh_P person 1 number pl gender f case d number pl parsarg kA ",
"sh_P person 1 number pl gender f case o number sg parsarg kA ",
"sh_P person 1 number pl gender f case o number pl parsarg kA ",
"sh_P person any number any gender m case d number sg parsarg kA ",
"sh_P person any number any gender m case d number pl parsarg kA ",
"sh_P person any number any gender m case o number sg parsarg kA ",
"sh_P person any number any gender m case o number pl parsarg kA ",
"sh_P person any number any gender f case d number sg parsarg kA ",
"sh_P person any number any gender f case d number pl parsarg kA ",
"sh_P person any number any gender f case o number sg parsarg kA ",
"sh_P person any number any gender f case o number pl parsarg kA ",
"adj gender any number any case any ",
"adj gender m number s case any ",
"adj gender f number s case any ",
"adj gender f number any case any ",
"adj gender m number sg case d ",
"adj gender m number sg case o ",
"adj gender m number pl case d ",
"adj gender m number pl case o ",
"adj gender any number any case d ",
"adj gender any number any case o ",
"v tam nA gender m number sg person any ",
"v tam nA gender m number pl person any ",
"v tam nA gender f number sg person any ",
"v tam nA gender f number pl person any ",
"v tam wA gender m number sg person any ",
"v tam wA gender m number pl person any ",
"v tam wA gender f number sg person any ",
"v tam wA gender f number pl person any ",
"v tam 0 gender any number any person any ",
"sh_n gender m number sg case d parsarg kA ",
"sh_n gender m number sg case o parsarg kA ",
"sh_n gender m number pl case d parsarg kA ",
"sh_n gender m number pl case o parsarg kA ",
"sh_n gender f number sg case d parsarg kA ",
"sh_n gender f number sg case o parsarg kA ",
"sh_n gender f number pl case d parsarg kA ",
"sh_n gender f number pl case o parsarg kA ",
};
